// app/scan-qr.tsx - Scan QR codes to import match data
import { parseQRPayload } from '@/services/qrCodeService';
import { db } from '@/services/database';
import { router } from 'expo-router';
import { useCallback, useState } from 'react';
import {
  ActivityIndicator,
  Modal,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import { SafeAreaView } from 'react-native-safe-area-context';

type ResultModal = { type: 'invalid' } | { type: 'imported'; saved: number; total: number } | { type: 'failed' } | null;

export default function ScanQrScreen() {
  const [permission, requestPermission] = useCameraPermissions();
  const [scanning, setScanning] = useState(true);
  const [importedCount, setImportedCount] = useState(0);
  const [resultModal, setResultModal] = useState<ResultModal>(null);

  const dismissModal = useCallback((goBack = false) => {
    setResultModal(null);
    if (goBack) {
      router.back();
    } else {
      setScanning(true);
    }
  }, []);

  const handleBarCodeScanned = useCallback(
    async ({ data }: { type: string; data: string }) => {
      if (!scanning) return;
      setScanning(false);

      const matches = parseQRPayload(data);
      if (matches.length === 0) {
        setResultModal({ type: 'invalid' });
        return;
      }

      try {
        await db.init();
        let saved = 0;
        for (const match of matches) {
          try {
            await db.saveMatch(match);
            saved++;
          } catch (e) {
            console.warn('Failed to save match:', match.id, e);
          }
        }
        setImportedCount((c) => c + saved);
        setResultModal({ type: 'imported', saved, total: matches.length });
      } catch (error) {
        console.error('Import failed:', error);
        setResultModal({ type: 'failed' });
      }
    },
    [scanning]
  );

  if (!permission) {
    return (
      <SafeAreaView style={styles.container} edges={['top', 'bottom']}>
        <View style={styles.centerContent}>
          <Text style={styles.message}>Requesting camera access...</Text>
        </View>
      </SafeAreaView>
    );
  }

  if (!permission.granted) {
    return (
      <SafeAreaView style={styles.container} edges={['top', 'bottom']}>
        <View style={styles.centerContent}>
          <Text style={styles.message}>
            Camera permission is required to scan QR codes.
          </Text>
          <TouchableOpacity style={styles.button} onPress={requestPermission}>
            <Text style={styles.buttonText}>Grant Permission</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container} edges={['top', 'bottom']}>
      <View style={styles.header}>
        <Text style={styles.title}>Scan QR Code</Text>
        <Text style={styles.subtitle}>
          Point to a QR code generated by a team member
        </Text>
        {importedCount > 0 && (
          <Text style={styles.importedText}>
            {importedCount} match{importedCount !== 1 ? 'es' : ''} imported
          </Text>
        )}
      </View>

      <View style={styles.cameraContainer}>
        <CameraView
          style={styles.camera}
          facing="back"
          barcodeScannerSettings={{ barcodeTypes: ['qr'] }}
          onBarcodeScanned={scanning ? handleBarCodeScanned : undefined}
        />
        {!scanning && (
          <View style={styles.scanOverlay}>
            <ActivityIndicator size="large" color="#ff6600" />
            <Text style={styles.scanOverlayText}>Processing...</Text>
          </View>
        )}
      </View>

      <Modal
        visible={resultModal !== null}
        transparent
        animationType="fade"
        onRequestClose={() => dismissModal(false)}
      >
        <TouchableOpacity
          style={styles.modalOverlay}
          activeOpacity={1}
          onPress={() => dismissModal(false)}
        >
          <View style={styles.modalContent} onStartShouldSetResponder={() => true}>
            {resultModal?.type === 'invalid' && (
              <>
                <Text style={styles.modalTitle}>Invalid QR Code</Text>
                <Text style={styles.modalMessage}>
                  This QR code does not contain valid match data.
                </Text>
                <TouchableOpacity style={styles.modalButton} onPress={() => dismissModal(false)}>
                  <Text style={styles.modalButtonText}>OK</Text>
                </TouchableOpacity>
              </>
            )}
            {resultModal?.type === 'imported' && (
              <>
                <Text style={styles.modalTitle}>Imported</Text>
                <Text style={styles.modalMessage}>
                  Imported {resultModal.saved} match{resultModal.saved !== 1 ? 'es' : ''} to My Data.
                  {resultModal.total > 1 ? '\n\nScan another QR code for more matches.' : ''}
                </Text>
                <View style={styles.modalButtonRow}>
                  <TouchableOpacity
                    style={[styles.modalButton, styles.modalButtonSecondary]}
                    onPress={() => dismissModal(false)}
                  >
                    <Text style={styles.modalButtonText}>Scan Another</Text>
                  </TouchableOpacity>
                  <TouchableOpacity style={styles.modalButton} onPress={() => dismissModal(true)}>
                    <Text style={styles.modalButtonText}>Done</Text>
                  </TouchableOpacity>
                </View>
              </>
            )}
            {resultModal?.type === 'failed' && (
              <>
                <Text style={styles.modalTitle}>Import Failed</Text>
                <Text style={styles.modalMessage}>
                  Could not save matches. Please try again.
                </Text>
                <TouchableOpacity style={styles.modalButton} onPress={() => dismissModal(false)}>
                  <Text style={styles.modalButtonText}>OK</Text>
                </TouchableOpacity>
              </>
            )}
          </View>
        </TouchableOpacity>
      </Modal>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a1a',
  },
  header: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#333',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    color: '#b0b0b0',
    marginBottom: 4,
  },
  importedText: {
    fontSize: 13,
    color: '#22c55e',
    marginTop: 4,
  },
  cameraContainer: {
    flex: 1,
    position: 'relative',
  },
  camera: {
    flex: 1,
  },
  scanOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scanOverlayText: {
    color: '#fff',
    fontSize: 16,
    marginTop: 12,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  message: {
    fontSize: 16,
    color: '#b0b0b0',
    textAlign: 'center',
    marginBottom: 24,
  },
  button: {
    backgroundColor: '#ff6600',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginBottom: 16,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalContent: {
    backgroundColor: '#2a2a2a',
    borderRadius: 12,
    padding: 24,
    width: '100%',
    maxWidth: 320,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 12,
    textAlign: 'center',
  },
  modalMessage: {
    fontSize: 15,
    color: '#b0b0b0',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 22,
  },
  modalButton: {
    backgroundColor: '#ff6600',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    flex: 1,
  },
  modalButtonSecondary: {
    backgroundColor: '#444',
  },
  modalButtonRow: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
